-- 031: user_spot mobile-sync columns
--
-- Adds:
--   client_uuid          — UUID v4, generated on mobile when spot is created.
--                          Used as idempotency key for offline-first sync via
--                          POST /api/mobile/spots/sync. Web doesn't set this
--                          (NULL allowed), so the column is UNIQUE only
--                          where NOT NULL (partial unique index).
--   client_updated_at    — last edit timestamp from the mobile client; used
--                          for last-write-wins conflict resolution on sync.
--   deleted_at           — soft-delete tombstone, so sync can propagate
--                          deletions without re-creating the row on the
--                          other device.
--
-- See docs/mobile-app-2026-05.md, section «Спот-синхронизация (offline-first)».

ALTER TABLE user_spot
    ADD COLUMN client_uuid       UUID,
    ADD COLUMN client_updated_at TIMESTAMPTZ,
    ADD COLUMN deleted_at        TIMESTAMPTZ;

CREATE UNIQUE INDEX user_spot_client_uuid_unique
    ON user_spot(client_uuid)
    WHERE client_uuid IS NOT NULL;

CREATE INDEX user_spot_deleted_at_idx
    ON user_spot(deleted_at)
    WHERE deleted_at IS NOT NULL;

COMMENT ON COLUMN user_spot.client_uuid IS
    'UUID v4 generated by mobile client. Idempotency key for /api/mobile/spots/sync. NULL for web-created spots.';
COMMENT ON COLUMN user_spot.client_updated_at IS
    'Mobile-side updated_at (Unix ms wrapped to TIMESTAMPTZ). Used for last-write-wins conflict resolution on sync.';
COMMENT ON COLUMN user_spot.deleted_at IS
    'Soft-delete tombstone. Mobile sets this; web returns the spot in /api/cabinet/spots only WHERE deleted_at IS NULL.';
