// AUTO-GENERATED by scripts/gen_district_accents.py — do not edit by hand.
//
// 18 hue-distinct earthy accents for Leningrad Oblast districts.
// Used as «district identity» dot/border (Wildsam Field-Guides move),
// independent from the forecast --idx-0..4 scale.
//
// Algorithm: HSL hue spread 360°/18 ≈ 20°, saturation 0.45,
// lightness 0.42; nudge for the 25–50° amber-clash zone with --idx-4.

export type DistrictOsmId = number;

export const DISTRICT_ACCENTS: Record<DistrictOsmId, string> = {
  390099: "#9b5e3b",  // Сосновоборский городской округ (hue 22.0°)
  391133: "#9b923b",  // Ломоносовский район (hue 54.0°)
  393909: "#989b3b",  // Кингисеппский район (hue 62.0°)
  393977: "#789b3b",  // Сланцевский район (hue 82.0°)
  1116466: "#589b3b",  // Кировский район (hue 102.0°)
  1117608: "#3b9b3e",  // Приозерский район (hue 122.0°)
  1118633: "#3b9b5e",  // Тихвинский район (hue 142.0°)
  1118829: "#3b9b7e",  // Подпорожский район (hue 162.0°)
  1124135: "#3b989b",  // Лодейнопольский район (hue 182.0°)
  1127515: "#3b789b",  // Бокситогорский район (hue 202.0°)
  1127562: "#3b589b",  // Киришский район (hue 222.0°)
  1128773: "#3e3b9b",  // Волховский район (hue 242.0°)
  1128809: "#5e3b9b",  // Тосненский район (hue 262.0°)
  1130269: "#7e3b9b",  // Гатчинский муниципальный округ (hue 282.0°)
  1130439: "#9b3b98",  // Лужский район (hue 302.0°)
  1145712: "#9b3b78",  // Волосовский район (hue 322.0°)
  1162549: "#9b3b58",  // Всеволожский район (hue 342.0°)
  1162550: "#9b3e3b",  // Выборгский район (hue 2.0°)
} as const;

export const DISTRICT_NAMES: Record<DistrictOsmId, string> = {
  390099: "Сосновоборский городской округ",
  391133: "Ломоносовский район",
  393909: "Кингисеппский район",
  393977: "Сланцевский район",
  1116466: "Кировский район",
  1117608: "Приозерский район",
  1118633: "Тихвинский район",
  1118829: "Подпорожский район",
  1124135: "Лодейнопольский район",
  1127515: "Бокситогорский район",
  1127562: "Киришский район",
  1128773: "Волховский район",
  1128809: "Тосненский район",
  1130269: "Гатчинский муниципальный округ",
  1130439: "Лужский район",
  1145712: "Волосовский район",
  1162549: "Всеволожский район",
  1162550: "Выборгский район",
} as const;

/** Fallback for unknown osm_ids — neutral moss. */
export const DEFAULT_ACCENT = "#7a9b64";

export function districtAccent(osmId: number): string {
  return DISTRICT_ACCENTS[osmId] ?? DEFAULT_ACCENT;
}
