"""Generate `packages/tokens/src/district-accents.ts`.

Each of the 18 admin_level=6 districts of Leningrad Oblast gets a stable
hue-distinct accent (the «Wildsam Field-Guides» move from
docs/redesign-2026-04.md). Decoupled from the forecast `--idx-0..4`
scale: this is district *identity*, not the day's index.

Source of districts: `data/osm/admin_districts_lenoblast.geojson`
(downloaded by `scripts/download_districts_overpass.py`).

Hue algorithm: 18 hues spread 360°/18 ≈ 20° apart, starting at 22°
(warm-red side). Saturation 0.45, lightness 0.42 — muted, earthy. We
nudge any hue that lands inside the 25–50° amber band so it doesn't
clash with `--idx-4` (#d88c1e ≈ hue 35°).

If the canonical palette is ever revised, re-run this script and commit
the regenerated .ts file.

Usage::

    PYTHONIOENCODING=utf-8 .venv/Scripts/python.exe \\
        scripts/gen_district_accents.py \\
        > packages/tokens/src/district-accents.ts
"""

from __future__ import annotations

import colorsys
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DISTRICTS_GEOJSON = REPO_ROOT / "data" / "osm" / "admin_districts_lenoblast.geojson"

SAT = 0.45
LIT = 0.42
START_DEG = 22.0
EXCLUDE = (25.0, 50.0)  # amber clash with --idx-4
DEFAULT_ACCENT = "#7a9b64"  # neutral moss


def load_districts() -> list[tuple[int, str]]:
    with open(DISTRICTS_GEOJSON, encoding="utf-8") as f:
        fc = json.load(f)
    rows: list[tuple[int, str]] = []
    for ft in fc.get("features", []):
        p = ft.get("properties") or {}
        osm_id = p.get("osm_rel_id")
        name = (p.get("name_ru") or "").strip()
        if osm_id is None or not name:
            continue
        rows.append((int(osm_id), name))
    rows.sort(key=lambda r: r[0])  # deterministic by osm_id
    return rows


def hue_for_index(i: int, n: int) -> float:
    h = (START_DEG + i * 360.0 / n) % 360.0
    if EXCLUDE[0] <= h <= EXCLUDE[1]:
        h = (h + 12.0) % 360.0
    return h


def hsl_to_hex(h_deg: float, s: float, l: float) -> str:
    r, g, b = colorsys.hls_to_rgb(h_deg / 360.0, l, s)
    return f"#{int(round(r * 255)):02x}{int(round(g * 255)):02x}{int(round(b * 255)):02x}"


def render_ts(districts: list[tuple[int, str]]) -> str:
    n = len(districts)
    rows = []
    for i, (osm_id, name) in enumerate(districts):
        h = hue_for_index(i, n)
        rows.append((osm_id, name, hsl_to_hex(h, SAT, LIT), round(h, 1)))

    out = []
    out.append("// AUTO-GENERATED by scripts/gen_district_accents.py — do not edit by hand.")
    out.append("//")
    out.append("// 18 hue-distinct earthy accents for Leningrad Oblast districts.")
    out.append("// Used as «district identity» dot/border (Wildsam Field-Guides move),")
    out.append("// independent from the forecast --idx-0..4 scale.")
    out.append("//")
    out.append("// Algorithm: HSL hue spread 360°/18 ≈ 20°, saturation 0.45,")
    out.append("// lightness 0.42; nudge for the 25–50° amber-clash zone with --idx-4.")
    out.append("")
    out.append("export type DistrictOsmId = number;")
    out.append("")
    out.append("export const DISTRICT_ACCENTS: Record<DistrictOsmId, string> = {")
    for osm_id, name, hex_str, h in rows:
        out.append(f'  {osm_id}: "{hex_str}",  // {name} (hue {h}°)')
    out.append("} as const;")
    out.append("")
    out.append("export const DISTRICT_NAMES: Record<DistrictOsmId, string> = {")
    for osm_id, name, _, _ in rows:
        out.append(f'  {osm_id}: "{name}",')
    out.append("} as const;")
    out.append("")
    out.append("/** Fallback for unknown osm_ids — neutral moss. */")
    out.append(f'export const DEFAULT_ACCENT = "{DEFAULT_ACCENT}";')
    out.append("")
    out.append("export function districtAccent(osmId: number): string {")
    out.append("  return DISTRICT_ACCENTS[osmId] ?? DEFAULT_ACCENT;")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main() -> None:
    districts = load_districts()
    if len(districts) != 18:
        print(
            f"warning: expected 18 districts, got {len(districts)}",
            file=sys.stderr,
        )
    sys.stdout.write(render_ts(districts))


if __name__ == "__main__":
    main()
